# Generated by Django 5.1.7 on 2025-03-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_rename_username_patient_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Umumiy', 'Umumiy'), ('Bolajon', 'Bolajon'), ('Nuroniy', 'Nuroniy'), ('Baxtli Oila', 'Baxtli Oila'), ('Kardio', 'Kardio'), ('Neyro', 'Neyro'), ('Onko', 'Onko')], max_length=50)),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=250)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('boshlamagan', 'Boshlamagan'), ('jarayonda', 'Jarayonda'), ('tugatgan', 'Tugatgan')], default='boshlamagan', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='telegram_bot.patient')),
            ],
        ),
    ]
