# Generated by Django 5.1.7 on 2025-03-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_testquestion_usertest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='subcategory',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
